version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: pg-Dockerfile.dockerfile
    env_file: ./.db.env
    # Comment the following if you don't want to keep your postgres data around on your disk.
    volumes:
      # This will write to a local directory called 'postgres_data'
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    # run boot.sh as docker ENTRYPOINT command
    entrypoint: ./boot.sh
    env_file: ./.env
    volumes:
      # Relative path map to listen to directory changes
      - ./:/usr/src/app/
    ports:
      - "5001:5001"
    depends_on:
      - db
      - redis
      - selenium

  redis:
    build:
      context: .
      dockerfile: redis-Dockerfile.dockerfile
    env_file: ./.redis.env
    volumes:
      - "redis_data:/data"
    # ports:
    #   - "6379:6379"

  celery:
    # build same image but with different entrypoint command
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: celery
    command: worker -A celery_worker.celery --loglevel=info
    # don't run celery worker process as root
    user: nobody
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
      - web
      - db

  selenium:
    image: selenium/standalone-chrome:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"

volumes:
  postgres_data:
  redis_data:
